### ISSUE TITLE
AWS docs indicate user data is base64 encoded, but tiny-ec2-bootstrap works without 

### ISSUE THREAD

**Issue by cmosier** [mcrute/tiny-ec2-bootstrap#24]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-add-user-data.html (and other places) indicate that AWS intends for user data to be base64 encoded, and will automatically encode it using the AWS CLI, etc.

If I encode (python boto3 in create_instances) user data in base64, it gets ignored.  Works fine if I don't encode.

**Comment by tomalok** [comment]
@cmosier -- you might want to double check to see whether boto3 is automagically base64 encoding the user data for you.

I'm looking at my personal Terraform, and the `aws_launch_template` resource, I'm doing the encoding explicitly...
```
resource aws_launch_template "foo" {
  # ...
  user_data = base64encode(
    templatefile("path-to-userdata/userdata.sh", 
      thing = var.thing
      # ...
    )
  )
  # ...
}
```

**Comment by cmosier** [comment]
@tomalok  thanks for the suggestion.  The boto3 docs are pretty light, and link to other docs that suggest the encoding is necessary....however, when I retrive the user doc from awscli, it is properly encoded.
