### ISSUE TITLE
allow configuration of default user

### ISSUE THREAD

**Issue by tomalok** [mcrute/tiny-ec2-bootstrap#3]
per conversation at mcrute/alpine-ec2-ami#51...

support an `/etc/conf.d/tiny-ec2-bootstrap` file that can be `source`d to provide overrides for `tiny-ec2-bootstrap` defaults.

something like...
```
EC2_USER="custom"
```
...to specify to use the user `custom` instead of the default `alpine`.

**Comment by tomalok** [comment]
should be easy enough to do this...  will submit a PR soon...  would be nice to get this package updated for 3.10.0.

**Comment by mcrute** [comment]
Fixed by #4
