### ISSUE TITLE
Print /var/log/cloud-bootstrap.log to console

### ISSUE THREAD

**Issue by mleonhard** [mcrute/tiny-ec2-bootstrap#5]
Thanks for your work on this project.  I'm trying to debug a user-data script and having trouble getting the output.  There's nothing in the EC2 console log.  I need to see the contents of /var/log/cloud-bootstrap.log.  How about unconditionally cat'ing that file to the console along with the exit status of the user-data script?

**Comment by mcrute** [comment]
Submitted [release 1.3.1 to upstream](https://gitlab.alpinelinux.org/alpine/aports/merge_requests/30240) that contains this change.
